retail:
 target: dev
 outputs:
  dev:
    type: bigquery
    method: service-account
    keyfile: /usr/local/airflow/include/gcp/service_account_key.json
    project: airflow-pipeline-404815
    dataset: retail
    threads: 1
    timeout_seconds: 300
    location: US